name = "TestTask"
version = "0.1.0"
defaultTargets = ["testtask"]

[[lean_lib]]
name = "TestTask"

[[lean_exe]]
name = "testtask"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0"